name: Sync release branch

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-cms-master:
    name: Merge main branch into release after a tag was created
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: main
          target: release
